@baseUrl =http://localhost:5000
@urlPath =api/v1

### 
put {{baseUrl}}/{{urlPath}}/user/follow/645145f3e40b8d8fbe7b7abb
Content-Type: application/json
Accept: : application/json
withCredentials: true

{
}

### 
put {{baseUrl}}/{{urlPath}}/user/unfollow/645123bd2d88a41590fadb80/6450d0c181760452efa80cf1
Content-Type: application/json
Accept: : application/json
withCredentials: true

{
}

### 
get {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: : application/json
withCredentials: true

{
}

### 
get {{baseUrl}}/{{urlPath}}/user/followers/645145f3e40b8d8fbe7b7abb
Content-Type: application/json
Accept: : application/json
withCredentials: true

{
}